name: Update Google Sheets

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel API
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
            ${{ secrets.SITE_DOMAIN }}/api/update
